(define (make-account balance password)
  (define (withdraw amount)
    (if (>= balance amount)
      (begin (set! balance (- balance amount))
             balance)
      "Insufficient funds"))

  (define (deposit amount)
    (set! balance (+ balance amount)))

  (define (dispatch input-password m)
    (if (eq? password input-password)
      (cond ((eq? m 'withdraw)
        withdraw)
      ((eq? m 'deposit)
        deposit)
      (else (error "Unknow request -- MAKE-ACCOUNT" m)))
    (lambda (useless-arg) (display "Incorrect password"))))
  dispatch)

(define acc (make-account 100 'secret-password))
((acc 'secret-password 'withdraw) 40)
((acc 'invalid-password 'deposit) 50)