(define (make-semaphore n)
  (let ((mutex (make-mutex)))
    (define (acquire)
      (mutex 'acquire)
      (if (> n 0)
        (begin (set! n (- n 1))
               (mutex 'release)
               'ok)
        (begin (mutex 'release)
               (acquire))))
    (define (release)
      (mutex 'acquire)
      (set! n (+ n 1))
      (mutex 'release)
      'ok)
    (define (dispatch mode)
      (cond ((eq? mode 'acquire)
              (acquire))
        ((eq? mode 'release)
              (release))
        (else
          error "Unkown mode MAKE-SEMAPHORE" mode)))
  dispatch))